### ISSUE TITLE
Import modules in code (python) node

### ISSUE THREAD

**Issue by D8mbSniper** [Rbillon59/hass-n8n#63]
Hi! First of all, thanks for the nice addon. Works like a charm with the Cloudflared. 

Still, i have a difficulty when trying to import a python module in a code node. Accourding to the offical [documetation ](https://docs.n8n.io/code/code-node/#python) n8n downloads the package automatically the first time you use it, but in my case something is wrong and i seean an error every time I try importing. 

Is it something with the build for HA or i am doing something incorrect?

![image](https://github.com/Rbillon59/hass-n8n/assets/17141491/80d1bd4e-d0f1-4b65-8bd6-937919d0833d)

I'm using the latest 1.0.15 vesion of an addon

**Comment by Rbillon59** [comment]
Hello,

I never try such things yet, I will take a closer look next week.

But the error message seems saying that your python code need to return an array or a dict, and may be failing because you're not returning anything.

Could you try to add a return statement, even empty, or with dummy values ?

Like `return {}` or `return {"foo":"bar"}`

**Comment by D8mbSniper** [comment]
Yeah, my bad. This code works, thanks for a correction! 

`foo = [{'name': 'Bob', 'age': 30},{'name': 'Tom', 'age': 23}]
print(foo[1])
return foo`
